Enhanced the test_* tools to do the most meaningful test first so that ICMP echo (ping) is no longer required in any case (see Novell/Suse Bugzilla bnc#616706). This is an enhancement for after openSUSE 11.3 Increased VERSION to 2.19.14
svn path=/trunk/printer/; revision=62178

diff --git a/tools/test_remote_novell b/tools/test_remote_novell
--- a/tools/test_remote_novell
+++ b/tools/test_remote_novell
@@ -2,11 +2,12 @@
 #
 # Test ability to connect to remote IPX Novell server.
 #
-# Exits:   0 doesn't seem to have a problem
-#          1 remote host $1 or queue $2 not set
-#          4 queue does not accept a print job (queue may not exist or queueing disabled?)
-#         (10=ping,11=netcat,12=fuser,13=mktemp,14=sed,15=lp,16=smbclient: see test_remote_smb)
-#         17 nprint not executable (no ncpfs RPM installed?)
+# Exits:   0 queue on host accepts print jobs
+#          1 host $1 or queue $2 not set
+#          4 queue does not accept a print job but host responds to a 'ping'
+#         10 queue does not accept a print job and ping not executable (no iputils RPM installed?)
+#         (11=netcat,12=fuser,13=mktemp,14=sed,15=lp,16=smbclient: see test_remote_smb)
+#         17 give up empty-handed because nprint not executable (no ncpfs RPM installed?)
 #
 # Johannes Meixner <jsmeix@suse.de>, 2000, 2002, 2007, 2008, 2009, 2010
 # Jan Holesovsky <kendy@suse.cz>, 2000
@@ -23,10 +24,6 @@ umask 022
 # Disable bash file name globbing:
 set -f
 
-# Use the binaries of the operating system (no aliases, functions, /usr/local/):
-export NPRINT=$( type -ap nprint | head -n 1 )
-[ -z "$NPRINT" ] && { echo -en "\nnprint not executable (no ncpfs RPM installed?)\n" 1>&2 ; exit 17 ; }
-
 MY_NAME=${0##*/}
 HOST=$1
 QUEUE=$2
@@ -34,12 +31,41 @@ QUEUE=$2
 USER=$3
 PASSWORD=$4
 TIMEOUT="$5"
-
 [ -z "$TIMEOUT" ] && TIMEOUT=10
 
-# test whether the queue on the server accepts print jobs
-echo -en "\r" | $NPRINT -S "$HOST" -U "$USER" -P "$PASSWORD" -q "$QUEUE" - 2>&1
-[ "$?" = "0" ] && { echo -en "\nQueue $QUEUE on host $HOST accepts print jobs\n" ; exit 0 ; }
-echo -en "\nQueue $QUEUE on host $HOST does not accept print jobs (queue may not exist or queueing disabled?)\n"
-exit 4
+# Use the binaries of the operating system (no aliases, functions, /usr/local/):
+export NPRINT=$( type -ap nprint | head -n 1 )
+
+# Test whether nprint is executable:
+if test -z "$NPRINT"
+then # Give up empty-handed when nprint is not executable because only the ping test is meaningless:
+     echo -en "\nGiving up empty-handed because 'nprint' not executable (no 'ncpfs' RPM installed?)\n" 1>&2
+     exit 17
+fi
+# Test whether the queue on the server accepts print jobs:
+echo -en "\nTesting queue '$QUEUE' on host '$HOST':\n"
+if echo -en "\r" | $NPRINT -S "$HOST" -U "$USER" -P "$PASSWORD" -q "$QUEUE" - 2>&1
+then echo -en "\nQueue '$QUEUE' on host '$HOST' accepts print jobs\n"
+     exit 0
+fi
+
+# The nprint test failed:
+echo -en "\nQueue '$QUEUE' on host '$HOST' does not accept print jobs (queue may not exist or queueing disabled?)\n\n"
+
+# Test whether ping is executable:
+if test -z "$PING"
+then # ping is not executable and the nprint test failed:
+     echo -en "\n'ping' not executable (no 'iputils' RPM installed?)\n" 1>&2
+     exit 10
+fi
+# Test whether host is accessible:
+if $PING -c 1 -w $TIMEOUT $HOST
+then # The ping test was successful but the nprint test failed:
+     echo -en "\nHost '$HOST' is accessible (responds to a 'ping')\n"
+     exit 4
+fi
+
+# Both the nprint test and the ping test failed:
+echo -en "\nHost '$HOST' unreachable (network issue or wrong host or firewall active?)\n"
+exit 2
 
diff --git a/tools/test_remote_smb b/tools/test_remote_smb
--- a/tools/test_remote_smb
+++ b/tools/test_remote_smb
@@ -2,13 +2,13 @@
 #
 # Test ability to connect to remote SMB server.
 #
-# Exits:   0 doesn't seem to have a problem
-#          1 remote host $1 or queue $2 not set
-#          2 the remote host $1 is unreachable (network issue or firewall active?)
-#          4 queue does not accept a print job (queue may not exist or queueing disabled?)
-#         10 ping not executable (no iputils RPM installed?)
+# Exits:   0 share on workgroup/host accepts print jobs
+#          1 host $2 or share $3 not set
+#          2 share does not accept a print job and host does not respond to a 'ping'
+#          4 share does not accept a print job but host responds to a 'ping'
+#         10 share does not accept a print job and ping not executable (no iputils RPM installed?)
 #         (11=netcat,12=fuser,13=mktemp,14=sed,15=lp: see test_remote_ipp)
-#         16 smbclient not executable (no samba-client RPM installed?)
+#         16 give up empty-handed because smbclient not executable (no samba-client RPM installed?)
 # The programs head, mkfifo, sleep, tr, rm are in the coreutils RPM and therefore assumed to exist.
 #
 # Johannes Meixner <jsmeix@suse.de>, 2000, 2002, 2007, 2008, 2009, 2010
@@ -26,31 +26,54 @@ umask 022
 # Disable bash file name globbing:
 set -f
 
-# Use the binaries of the operating system (no aliases, functions, /usr/local/):
-export PING=$( type -ap ping | head -n 1 )
-[ -z "$PING" ] && { echo -en "\nping not executable (no iputils RPM installed?)\n" 1>&2 ; exit 10 ; }
-export SMBCLIENT=$( type -ap smbclient | head -n 1 )
-[ -z "$SMBCLIENT" ] && { echo -en "\nsmbclient not executable (no samba-client RPM installed?)\n" 1>&2 ; exit 16 ; }
-
 MY_NAME=${0##*/}
 WORKGROUP=$1
 HOST=$2
-QUEUE=$3
-[ -z "$HOST" -o -z "$QUEUE" ] && { echo -en "\nUsage:\n$MY_NAME WORKGROUP HOST QUEUE [USER] [PASS] [TIMEOUT]\n" 1>&2 ; exit 1 ; }
+SHARE=$3
+if test -z "$HOST" -o -z "$SHARE"
+then echo -en "\nUsage:\n$MY_NAME WORKGROUP HOST SHARE [USER] [PASSWORD] [TIMEOUT]\n" 1>&2
+     exit 1
+fi
 USER=$4
 PASSWORD=$5
 TIMEOUT="$6"
-
 [ -z "$TIMEOUT" ] && TIMEOUT=10
 
-# test whether the remote host is accessible
-$PING -c 1 -w $TIMEOUT $HOST || { echo -en "\nHost $HOST unreachable (network issue or firewall active?)\n" ; exit 2 ; }
+# Use the binaries of the operating system (no aliases, functions, /usr/local/):
+export PING=$( type -ap ping | head -n 1 )
+export SMBCLIENT=$( type -ap smbclient | head -n 1 )
 
-# test whether the queue on the server accepts print jobs
-echo -e "\nTesting $QUEUE on $WORKGROUP/$HOST:"
+# Test whether smbclient is executable:
+if test -z "$SMBCLIENT"
+then # Give up empty-handed when smbclient is not executable because only the ping test is meaningless:
+     echo -en "\nGiving up empty-handed because 'smbclient' not executable (no 'samba-client' RPM installed?)\n" 1>&2
+     exit 16
+fi
+# Test whether the SMB share on the server accepts print jobs:
+echo -en "\nTesting share '$SHARE' on '$WORKGROUP/$HOST':\n"
 test -z "$PASSWORD" && PASSWORD="-N"
-echo -en "\r" | $SMBCLIENT "//$HOST/$QUEUE" "$PASSWORD" -c "print -" -U "$USER" -W "$WORKGROUP"
-[ "$?" = "0" ] && { echo -en "\nShare $QUEUE on $WORKGROUP/$HOST accepts print jobs\n" ; exit 0 ; }
-echo -en "\nShare $QUEUE on $WORKGROUP/$HOST does not accept print jobs (queue may not exist or queueing disabled?)\n"
-exit 4
+if echo -en "\r" | $SMBCLIENT "//$HOST/$SHARE" "$PASSWORD" -c "print -" -U "$USER" -W "$WORKGROUP"
+then echo -en "\nShare '$SHARE' on '$WORKGROUP/$HOST' accepts print jobs\n"
+     exit 0
+fi
+
+# The smbclient test failed:
+echo -en "\nShare '$SHARE' on '$WORKGROUP/$HOST' does not accept print jobs (share may not exist?)\n\n"
+
+# Test whether ping is executable:
+if test -z "$PING"
+then # ping is not executable and the smbclient test failed:
+     echo -en "\n'ping' not executable (no 'iputils' RPM installed?)\n" 1>&2
+     exit 10
+fi
+# Test whether host is accessible:
+if $PING -c 1 -w $TIMEOUT $HOST
+then # The ping test was successful but the smbclient test failed:
+     echo -en "\nHost '$HOST' is accessible (responds to a 'ping')\n"
+     exit 4
+fi
+
+# Both the smbclient test and the ping test failed:
+echo -en "\nHost '$HOST' unreachable (network issue or wrong host or firewall active?)\n"
+exit 2
 
diff --git a/tools/test_remote_socket b/tools/test_remote_socket
--- a/tools/test_remote_socket
+++ b/tools/test_remote_socket
@@ -2,13 +2,13 @@
 #
 # Test ability to connect to remote direct socket (JetDirect) server.
 #
-# Exits:   0 doesn't seem to have a problem
-#          1 remote host $1 not set
-#          2 the remote host $1 is unreachable (network issue or firewall active?)
-#          3 no connection possible to port 9100 or port $2 on host $1 (wrong port or firewall active there?)
-#          4 port 9100 or port $2 on host $1 does not accept data (wrong port or firewall active there?)
-#         10 ping not executable (no iputils RPM installed?)
-#         11 netcat not executable (no netcat RPM installed?)
+# Exits:   0 port on host accepts data
+#          1 host $1 not set
+#          2 no connection possible to port on host and host does not respond to a 'ping'
+#          3 no connection possible to port on host but host responds to a 'ping'
+#          4 connection possible to port on host but does not accept data
+#         10 no connection possible to port on host and ping not executable (no iputils RPM installed?)
+#         11 give up empty-handed because netcat not executable (no netcat RPM installed?)
 # The program head is in the coreutils RPM and therefore assumed to exist.
 #
 # Johannes Meixner <jsmeix@suse.de> 2002, 2007, 2008, 2009, 2010
@@ -25,12 +25,6 @@ umask 022
 # Disable bash file name globbing:
 set -f
 
-# Use the binaries of the operating system (no aliases, functions, /usr/local/):
-export PING=$( type -ap ping | head -n 1 )
-[ -z "$PING" ] && { echo -en "\nping not executable (no iputils RPM installed?)\n" 1>&2 ; exit 10 ; }
-export NETCAT=$( type -ap netcat | head -n 1 )
-[ -z "$NETCAT" ] && { echo -en "\nnetcat not executable (no netcat RPM installed?)\n" 1>&2 ; exit 11 ; }
-
 MY_NAME=${0##*/}
 HOST="$1"
 [ -z "$HOST" ] && { echo -en "\nUsage:\n$MY_NAME HOST [PORT [TIMEOUT]]\n" 1>&2 ; exit 1 ; }
@@ -39,15 +33,45 @@ PORT="$2"
 TIMEOUT="$3"
 [ -z "$TIMEOUT" ] && TIMEOUT=10
 
-# test whether the remote host is accessible
-$PING -c 1 -w $TIMEOUT $HOST || { echo -en "\nHost $HOST unreachable (network issue or firewall active?)\n" ; exit 2 ; }
+# Use the binaries of the operating system (no aliases, functions, /usr/local/):
+export NETCAT=$( type -ap netcat | head -n 1 )
+export PING=$( type -ap ping | head -n 1 )
 
-# test whether connection is possible to $PORT on the remote host
-$NETCAT -w $TIMEOUT -z $HOST $PORT || { echo -en "\nNo connection possible to port $PORT on host $HOST (wrong port or firewall active there?)\n" ; exit 3 ; }
+# Test whether netcat is executable:
+if test -z "$NETCAT"
+then # Give up empty-handed when netcat is not executable because only the ping test is meaningless:
+     echo -en "\nGiving up empty-handed because 'netcat' not executable (no 'netcat' RPM installed?)\n" 1>&2
+     exit 11
+fi
+# Test whether connection is possible to port on host:
+if $NETCAT -w $TIMEOUT -z $HOST $PORT
+then # Test whether port on host accepts data:
+     if echo -en "\r" | $NETCAT -w $TIMEOUT $HOST $PORT 2>&1
+     then echo -en "\nPort '$PORT' on host '$HOST' accepts data\n"
+          exit 0
+     fi
+     echo -en "\nConnection possible to port '$PORT' on host '$HOST' but does not accept data\n"
+     exit 4
+fi
 
-# test whether $PORT on the remote host accepts data
-echo -en "\r" | $NETCAT -w $TIMEOUT $HOST $PORT 2>&1
-[ "$?" = "0" ] && { echo -en "\nPort $PORT on host $HOST accepts data\n" ; exit 0 ; }
-echo -en "\nPort $PORT on host $HOST does not accept data (wrong port or firewall active there?)\n"
-exit 4
+# The netcat test failed:
+echo -en "\nNo connection possible to port '$PORT' on host '$HOST' (wrong port or firewall active there?)\n\n"
+
+# Test whether ping is executable:
+if test -z "$PING"
+then # ping is not executable and the netcat test failed:
+     echo -en "\n'ping' not executable (no 'iputils' RPM installed?)\n" 1>&2
+     exit 10
+fi
+# Test whether host is accessible:
+if $PING -c 1 -w $TIMEOUT $HOST
+then # The ping test was successful but the netcat test failed:
+     echo -en "\nHost '$HOST' is accessible (responds to a 'ping')\n"
+     exit 3
+fi
+
+# Both the netcat test and the ping test failed:
+echo -en "\nHost '$HOST' unreachable (network issue or wrong host or firewall active?)\n"
+exit 2
+
 
